[workspace]
channels = ["conda-forge"]
name = "sim"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
matplotlib = ">=3.10.9,<4"
python = ">=3.12.13,<3.13"
packaging = ">=24.2,<26"
numpy = ">=2.0.0,<2.3.0"
mediapy = ">=1.2.6,<2"
sentencepiece = ">=0.2.0,<0.3"

[pypi-dependencies]
lerobot = { git = "https://github.com/huggingface/lerobot.git", extras = ["pi"] }
gym-so100 = ">=0.1.2, <0.2"
imageio = { version = ">=2.37.3, <3", extras = ["ffmpeg"] }
mujoco = "==3.8.1"
dm-control = "==1.0.41"
